# Generated by Django 4.2.27 on 2026-02-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturesession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONDUCTED', 'Conducted'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20),
        ),
    ]
