# Generated by Django 4.2.27 on 2026-03-05 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_courseunit_weekly_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0002_alter_lecturesession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_runs', to='academic.department')),
            ],
        ),
    ]
