# Generated by Django 4.2.27 on 2026-03-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_courseunit_weekly_hours'),
        ('scheduling', '0003_schedulingrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(default='Semester 1', max_length=50)),
                ('academic_year', models.CharField(default='2026/2027', max_length=20)),
                ('available_days', models.CharField(default='MON,TUE,WED,THU,FRI', max_length=50)),
                ('day_start_time', models.TimeField(default='08:00')),
                ('day_end_time', models.TimeField(default='17:00')),
                ('slot_duration_hours', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_params', to='academic.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
