# Generated by Django 4.2.27 on 2026-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_schedulingparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingparameters',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
