# Generated by Django 4.2.27 on 2026-03-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_schedulingparameters_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='recording_method',
            field=models.CharField(choices=[('DIGITAL', 'Direct System Entry'), ('PAPER', 'Paper-based Upload')], default='DIGITAL', max_length=10),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='signed_sheet',
            field=models.FileField(blank=True, null=True, upload_to='attendance_sheets/'),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
