# Generated by Django 4.2.27 on 2026-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_lecturesession_recording_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='actual_duration',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
    ]
