# Generated by Django 4.2.27 on 2026-03-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_lecturesession_actual_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingparameters',
            name='semester_name',
        ),
        migrations.AddField(
            model_name='schedulingparameters',
            name='cohort',
            field=models.CharField(choices=[('EASTER', 'Easter Intake'), ('TRINITY', 'Trinity Intake'), ('ADVENT', 'Advent Intake')], default='EASTER', max_length=10),
        ),
        migrations.AddField(
            model_name='schedulingparameters',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
    ]
