# Generated by Django 4.2.27 on 2026-03-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_coursegroup_course_units'),
        ('scheduling', '0008_remove_schedulingparameters_semester_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='course_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.coursegroup'),
        ),
    ]
