# Generated by Django 4.2.27 on 2026-03-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_timetableentry_course_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='scheduling_params',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.schedulingparameters'),
        ),
    ]
