# Generated by Django 4.2.27 on 2026-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_timetableentry_scheduling_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingparameters',
            name='semester',
        ),
        migrations.AddField(
            model_name='schedulingparameters',
            name='study_time',
            field=models.CharField(choices=[('DAY', 'Day'), ('EVENING', 'Evening'), ('WEEKEND', 'Weekend')], default='DAY', max_length=10),
        ),
    ]
