# Generated by Django 4.2.27 on 2026-03-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_remove_schedulingparameters_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='teaching_mode',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online')], default='PHYSICAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.room'),
        ),
    ]
