# Generated by Django 4.2.27 on 2026-03-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0012_timetableentry_teaching_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='verification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('CONDUCTED', 'Conducted'), ('SUBMITTED', 'Submitted'), ('PENDING_VERIFICATION', 'Pending Verification'), ('APPROVED', 'Approved'), ('AUTO_CONFIRMED', 'Auto-Confirmed'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled'), ('LECTURER_CONFIRMED', 'Lecturer Confirmed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
