# Generated by Django 4.2.27 on 2026-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_lecturesession_verification_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='lecturer_has_viewed',
            field=models.BooleanField(default=False, help_text='Has the lecturer opened the attendance list for review?'),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('CONDUCTED', 'Conducted'), ('SUBMITTED', 'Conducted & Attendance submitted'), ('PENDING_VERIFICATION', 'Pending Verification'), ('APPROVED', 'Approved'), ('AUTO_CONFIRMED', 'Auto-Confirmed'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled'), ('LECTURER_CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
