# Generated by Django 4.2.27 on 2026-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('HOD', 'Head of Department'), ('COORDINATOR', 'Coordinator'), ('LECTURER', 'Lecturer'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
