# Generated by Django 4.2.27 on 2026-02-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_courseunit_lecturer'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this user belongs to (for HODs, Lecturers, Students)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academic.department'),
        ),
    ]
