# Generated by Django 4.2.27 on 2026-02-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_number_lecturerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
    ]
