# Generated by Django 4.2.27 on 2026-03-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_lecturerprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('NOT_ACTIVATED', 'Not Activated'), ('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='NOT_ACTIVATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('FACULTY_ADMIN', 'Faculty Admin'), ('HOD', 'Head of Department'), ('COORDINATOR', 'Coordinator'), ('LECTURER', 'Lecturer'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
