# Generated by Django 4.2.27 on 2026-03-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_account_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
