# Generated by Django 4.2.27 on 2026-03-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_courseunit_weekly_hours'),
        ('users', '0007_user_requires_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, help_text='The program this student is enrolled in (for Students only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.program'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academic.department'),
        ),
    ]
