# Generated by Django 4.2.27 on 2026-03-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_courseunit_weekly_hours'),
        ('users', '0008_user_program_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_group',
            field=models.ForeignKey(blank=True, help_text='The specific class/group this student or coordinator is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academic.coursegroup'),
        ),
    ]
