# Generated by Django 4.2.27 on 2026-03-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_course_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='min_weekly_load',
            field=models.PositiveIntegerField(default=16, help_text='Minimum teaching hours per week'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='max_weekly_load',
            field=models.PositiveIntegerField(default=20, help_text='Maximum teaching hours per week'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('FACULTY_ADMIN', 'Faculty Admin'), ('HOD', 'Head of Department'), ('COORDINATOR', 'Coordinator'), ('LECTURER', 'Lecturer'), ('ADMIN_ASSISTANT', 'Administrative Assistant'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
