# Generated by Django 4.2.27 on 2026-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_lecturerprofile_min_weekly_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='academic_rank',
            field=models.CharField(choices=[('TA', 'Tutorial Assistant/Teaching Assistant'), ('AL', 'Assistant Lecturer'), ('L', 'Lecturer'), ('SL', 'Senior Lecturer')], default='L', help_text='The specific rank of the teaching staff', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('FACULTY_ADMIN', 'Faculty Admin'), ('HOD', 'Head of Department'), ('COORDINATOR', 'Coordinator'), ('LECTURER', 'Teaching Staff'), ('ADMIN_ASSISTANT', 'Administrative Assistant'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
