# Generated by Django 4.2.27 on 2026-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_lecturerprofile_academic_rank_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Administrator'), ('FACULTY_ADMIN', 'Faculty Admin'), ('HOD', 'Academic Administrator'), ('COORDINATOR', 'Coordinator'), ('LECTURER', 'Teaching Staff'), ('ADMIN_ASSISTANT', 'Administrative Assistant'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
