# Generated by Django 4.2.27 on 2026-03-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_access_no_user_coordinator_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_date',
            field=models.DateField(blank=True, help_text='Derived from registration number (e.g. J26 -> Jan 2026)', null=True),
        ),
    ]
