# Generated by Django 4.2.27 on 2026-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('COMPLIANCE', 'Compliance'), ('PERFORMANCE', 'Performance'), ('STRUCTURAL', 'Structural'), ('SECURITY', 'Security'), ('SYSTEM_HEALTH', 'System Health'), ('INTEGRITY', 'Integrity'), ('STUDENT_RISK', 'Student Risk'), ('OPERATIONAL', 'Operational'), ('REMINDER', 'Reminder'), ('TIMETABLE', 'Timetable'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
