# Generated by Django 4.2.27 on 2026-03-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_lecturesession_verification_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alert_category_alert_severity_alter_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='scheduling.lecturesession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
