# Generated by Django 4.2.27 on 2026-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_coursegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=2, help_text='Number of teaching hours per week'),
        ),
    ]
