# Generated by Django 4.2.27 on 2026-03-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_courseunit_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='course_type',
            field=models.CharField(choices=[('THEORY', 'Theoretical'), ('PRACTICAL', 'Practical')], default='THEORY', max_length=20),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='required_contact_hours',
            field=models.PositiveIntegerField(default=45, help_text='Minimum contact hours required (e.g., 45 for Theory, 60 for Practical)'),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=4, help_text='Number of teaching hours per week (Standard: 2 sessions * 2 hours = 4)'),
        ),
    ]
