# Generated by Django 4.2.27 on 2026-03-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_courseunit_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='max_years',
            field=models.PositiveIntegerField(default=5, help_text='Maximum allowed duration in years'),
        ),
        migrations.AddField(
            model_name='program',
            name='min_years',
            field=models.PositiveIntegerField(default=3, help_text='Minimum allowed duration in years'),
        ),
    ]
