# Generated by Django 4.2.27 on 2026-03-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_program_max_years_program_min_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1),
        ),
    ]
