# Generated by Django 4.2.27 on 2026-03-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_coursegroup_semester_coursegroup_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='course_units',
            field=models.ManyToManyField(blank=True, related_name='course_groups', to='academic.courseunit'),
        ),
    ]
