# Generated by Django 4.2.27 on 2026-03-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_coursegroup_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this group active for the current scheduling session?'),
        ),
    ]
