# Generated by Django 4.2.27 on 2026-03-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_coursegroup_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='course_category',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('FOUNDATIONAL', 'Foundational')], default='CORE', max_length=20),
        ),
    ]
