# Generated by Django 4.2.27 on 2026-04-03 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0011_courseunit_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2023/2024', max_length=20)),
                ('semester', models.PositiveIntegerField(choices=[(1, '1'), (2, '2')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_unit', models.ForeignKey(limit_choices_to={'course_category': 'ELECTIVE'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.courseunit')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='elective_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Elective Enrollments',
                'unique_together': {('student', 'course_unit', 'academic_year', 'semester')},
            },
        ),
    ]
