# Generated by Django 4.2.27 on 2026-04-03 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0012_electiveenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='assistant_coordinator',
            field=models.ForeignKey(blank=True, help_text='Course Unit Coordinator (Assistant Coordinator) for attendance management.', limit_choices_to={'role': 'COORDINATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
